apiVersion: v1
kind: Service
metadata:
  name: python-app-nodeport
  namespace: default
spec:
  selector:
    app: python-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort
